# First Steps with Numpy

Numpy is a package for scientific computing with Python. <br/>It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

In this notebook, we are gonna see some basic usage of numpy.

So, let the fun begin!!

In [0]:
# Essential imports
import numpy as np

## ndarray (N - Dimensional Array)

An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size.


In [2]:
# Define ndarray using np.array
# params
#   object - array object
#   dtype - The desired data-type for the array

np_arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype=np.int32)
np_arr_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float32)
np_arr_3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [5, 6, 7, 8]]], dtype=np.float64)

print (np_arr_1)
print ("--------------------------")
print (np_arr_2)
print ("--------------------------")
print (np_arr_3)

[1 2 3 4 5 6 7 8]
--------------------------
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
--------------------------
[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[1. 2. 3. 4.]
  [5. 6. 7. 8.]]]


In [3]:
# Define ndarray using np.zeros
# params
#   shape - shape of the resultant np.ndarray
#   dtype - The desired data-type for the array

np_zeros_1 = np.zeros(shape=(2), dtype=np.float32)
np_zeros_2 = np.zeros(shape=(2, 2), dtype=np.float64)
np_zeros_3 = np.zeros(shape=(2, 3, 2), dtype=np.int32)

print (np_zeros_1)
print ("--------------------------")
print (np_zeros_2)
print ("--------------------------")
print (np_zeros_3)

[0. 0.]
--------------------------
[[0. 0.]
 [0. 0.]]
--------------------------
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [4]:
# Check the type using type
print ('Type of np_arr_2 :', type (np_arr_2))
print ('Type of np_arr_3 :', type (np_arr_3))

Type of np_arr_2 : <class 'numpy.ndarray'>
Type of np_arr_3 : <class 'numpy.ndarray'>


In [5]:
# Check the type of elements present in the np.array
print ('Type of the element np_arr_1: ', np_arr_1.dtype)
print ('Type of the element np_arr_2: ', np_arr_2.dtype)
print ('Type of the element np_arr_3: ', np_arr_3.dtype)

Type of the element np_arr_1:  int32
Type of the element np_arr_2:  float32
Type of the element np_arr_3:  float64


In [6]:
# Check the shape of the ndarray
print ('Shape of the element np_arr_1: ', np_arr_1.shape)
print ('Shape of the element np_arr_2: ', np_arr_2.shape)
print ('Shape of the element np_arr_3: ', np_arr_3.shape)

Shape of the element np_arr_1:  (8,)
Shape of the element np_arr_2:  (2, 4)
Shape of the element np_arr_3:  (2, 2, 4)


In [7]:
# Accessing the elements in the ndarray

# The element in the second row and the first column 
print ('np_arr_2[1, 0] : ', np_arr_2[1, 0]) # since its 0-indexed

# Will return an np.array
print ('np_arr_3[0, 1] : ', np_arr_3[0, 1])

np_arr_2[1, 0] :  5.0
np_arr_3[0, 1] :  [5. 6. 7. 8.]


In [8]:
# Slicing
# Getting slices of np.ndarray

# All elements from the start till the 4th index (exclusive)
print ('np_arr_1[:4]    : ', np_arr_1[:4])

# All elements from the 4th index (inclusive) till the last element in the array
print ('np_arr_1[4:]    : ', np_arr_1[4:])

# All elements from the 3rd index (inclusive) till the 5th index (exclusive)
print ('np_arr_1[3:5]   : ', np_arr_1[3:5])

# Get all the rows from the first column
print ('np_arr_2[:, 1]  : ', np_arr_2[:, 1])

np_arr_1[:4]    :  [1 2 3 4]
np_arr_1[4:]    :  [5 6 7 8]
np_arr_1[3:5]   :  [4 5]
np_arr_2[:, 1]  :  [2. 6.]


In [11]:
# Get the Transpose of an ndarray with `.T`
np_arr_4 = np_arr_1.T
np_arr_5 = np_arr_2.T
np_arr_6 = np_arr_3.T

print ('Transposed shape of np_arr_1 is :', np_arr_4.shape, ' which originally was :', np_arr_1.shape)
print ('Transposed shape of np_arr_2 is :', np_arr_5.shape, ' which originally was :', np_arr_2.shape)
print ('Transposed shape of np_arr_3 is :', np_arr_6.shape, ' which originally was :', np_arr_3.shape)

Transposed shape of np_arr_1 is : (8,)  which originally was : (8,)
Transposed shape of np_arr_2 is : (4, 2)  which originally was : (2, 4)
Transposed shape of np_arr_3 is : (4, 2, 2)  which originally was : (2, 2, 4)


In [17]:
# Test whether ALL the elements in the array with a given axis evaluates to true
# with `.all`
# axis = 1 means by the row
# axis = 0 means by the column

np_bool_arr_1 = np.array([[True, True, True], [True, False, True]])

# Check if all the elements in the array evaluates to true
print ('Whether everything evaluates to true considering all elements in the array :', np_bool_arr_1.all())

# Check if each row evaluates to True
# Note: There are 2 rows, so we will get two values, one for each row
print ('Whether everything evaluates to true in axis 1 :', np_bool_arr_1.all(axis=1)) 

# Check if each column evaluates to True
# Note: There are 3 columns, so we will get three values, one for each column
print ('Whether everything evaluates to true in axis 0 :', np_bool_arr_1.all(axis=0))

Whether everything evaluates to true considering all elements in the array : False
Whether everything evaluates to true in axis 1 : [ True False]
Whether everything evaluates to true in axis 0 : [ True False  True]


In [19]:
# Test whether ANY of the element in the array with a given axis evaluates to true
# with `.any`
# axis = 1 means by the row
# axis = 0 means by the column

np_bool_arr_2 = np.array([[True, False, True], [True, False, True]])

# Check if all the elements in the array evaluates to true
print ('Whether everything evaluates to true considering all elements in the array :', np_bool_arr_1.any())

# Check if each row evaluates to True
# Note: There are 2 rows, so we will get two values, one for each row
print ('Whether everything evaluates to true in axis 1 :', np_bool_arr_1.any(axis=1)) 

# Check if each column evaluates to True
# Note: There are 3 columns, so we will get three values, one for each column
print ('Whether everything evaluates to true in axis 0 :', np_bool_arr_1.any(axis=0))

Whether everything evaluates to true considering all elements in the array : True
Whether everything evaluates to true in axis 1 : [ True  True]
Whether everything evaluates to true in axis 0 : [ True False  True]


In [22]:
# Get the *index* of the MAX element in the array with a given axis
# with `.argmax`
# axis = 1 means by the row
# axis = 0 means by the column

np_arr_7 = np.array([[34, 12, -65], [12, 56, -1], [45, 12, 67], [89, -34, 12]])

# Check if all the elements in the array evaluates to true
print ('The indexes of the MAX elements in the whole array :', np_arr_7.argmax())

# Check if each row evaluates to True
# Note: There are 2 rows, so we will get two values, one for each row
print ('The indexes of the MAX elements in axis 1 :', np_arr_7.argmax(axis=1)) 

# Check if each column evaluates to True
# Note: There are 3 columns, so we will get three values, one for each column
print ('The indexes of the MAX elements in axis 0 :', np_arr_7.argmax(axis=0))

The indexes of the MAX elements in the whole array : 9
The indexes of the MAX elements in axis 1 : [0 1 2 0]
The indexes of the MAX elements in axis 0 : [3 1 2]


In [23]:
# Get the *index* of the MIN element in the array with a given axis
# with `.argmin`
# axis = 1 means by the row
# axis = 0 means by the column

np_arr_8 = np.array([[37, 1, -65], [12, 563, -1], [95, 12, 67], [29, -3, 19]])

# Check if all the elements in the array evaluates to true
print ('The indexes of the MIN elements in the whole array :', np_arr_8.argmin())

# Check if each row evaluates to True
# Note: There are 2 rows, so we will get two values, one for each row
print ('The indexes of the MIN elements in axis 1 :', np_arr_8.argmin(axis=1)) 

# Check if each column evaluates to True
# Note: There are 3 columns, so we will get three values, one for each column
print ('The indexes of the MIN elements in axis 0 :', np_arr_8.argmin(axis=0))

The indexes of the MIN elements in the whole array : 2
The indexes of the MIN elements in axis 1 : [2 2 1 1]
The indexes of the MIN elements in axis 0 : [1 3 0]


In [24]:
# Get the *index* of the elements of the array that would sort the array
# with `.argsort`
# axis = 1 means by the row
# axis = 0 means by the column

np_arr_9 = np.array([[125, 31, -65], [84, 23, -17], [357, 84, 8], [231, -23, 9]])

# Check if all the elements in the array evaluates to true
print ('The indexes of the elements in the whole array that would sort them: ', np_arr_9.argsort())

# Check if each row evaluates to True
# Note: There are 2 rows, so we will get two values, one for each row
print ('The indexes of the elements in the whole array that would sort them in axis 1: ', np_arr_9.argsort(axis=1)) 

# Check if each column evaluates to True
# Note: There are 3 columns, so we will get three values, one for each column
print ('The indexes of the elements in the whole array that would sort them in axis 0:', np_arr_9.argsort(axis=0))

The indexes of the elements in the whole array that would sort them:  [[2 1 0]
 [2 1 0]
 [2 1 0]
 [1 2 0]]
The indexes of the elements in the whole array that would sort them in axis 1:  [[2 1 0]
 [2 1 0]
 [2 1 0]
 [1 2 0]]
The indexes of the elements in the whole array that would sort them in axis 0: [[1 3 0]
 [0 1 1]
 [3 0 2]
 [2 2 3]]


In [27]:
# Construct an array from an *index array* and a *set of arrays* to choose from.
# using np.choose

arrays_to_choose_from = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

# So the arrays_to_choose_from holds all the arrays where we will choose our elements from
# Now let's pass the index array to np.choose along with the arrays_to_choose_from
# An index array is one which holds the indexes

new_array_from_index_array_and_arrays_to_choose_from = np.choose([3, 1, 2, 0], arrays_to_choose_from)

# The result array will have
# The first element from the first element from the array at the 3rd index of arrays_to_choose_from i.e. 13
# The second element from the second element from the array at the 1st index of arrays_to_choose_from i.e. 6
# The third element from the third element from the array at the 2nd index of arrays_to_choose_from i.e. 11
# The fourth element from the fourth element from the array at the 0th index of arrays_to_choose_from i.e. 4

# Let's print to check out
print ('The new array is: ', new_array_from_index_array_and_arrays_to_choose_from)

The new array is:  [13  6 11  4]


In [31]:
# Get a evenly space values with a given interval
# using np.arange

np_arange_1 = np.arange(10)
np_arange_2 = np.arange(10, 15.45)
np_arange_3 = np.arange(10.23, 20.21, 2)

print ('The array with starting from 0 and ending at 10 with interval of 1        : ', np_arange_1)
print ('The array with starting from 10 and ending at 15.45 with interval of 1    : ', np_arange_2)
print ('The array with starting from 10.23 and ending at 20.21 with interval of 2 : ', np_arange_3)

The array with starting from 0 and ending at 10 with interval of 1        :  [0 1 2 3 4 5 6 7 8 9]
The array with starting from 10 and ending at 15.45 with interval of 1    :  [10. 11. 12. 13. 14. 15.]
The array with starting from 10.23 and ending at 20.21 with interval of 2 :  [10.23 12.23 14.23 16.23 18.23]


In [33]:
# Clip (or limit) the values in the array
# using np.clip

np_arange_4 = np.arange(34, 56, 3)

# Let's clip the values in the above array in between 45 and 50
# So all values less than 45 will be 45
# And all values greater than 50 will be 50
np_clipped_1 = np_arange_4.clip(45, 50)

print ('Original Array :', np_arange_4)
print ('Clipped Array  :', np_clipped_1)

Original Array : [34 37 40 43 46 49 52 55]
Clipped Array  : [45 45 45 45 46 49 50 50]


In [34]:
# Get the selected slices of an array along given axis
# using np.compress

np_arr_10 = np.array([[45, 23, 12, 56], 
                      [67, 2, 1, 5], 
                      [89, 3, 1, 0], 
                      [45, 67, 2, 1]])

# Get the elements based on bool_array and the axis
# If axis is None, a flattened array is considered
print ('Compressed array getting the 1st and last columns: ', np_arr_10.compress([True, False, False, True], axis=0))
print ('Compressed array getting the 1st and last rows: ', np_arr_10.compress([True, False, False, True], axis=1))
print ('Compressed array getting the 1st and 3rd columns: ', np_arr_10.compress([True, False, True, False], axis=0))

Compressed array getting the 1st and last columns:  [[45 23 12 56]
 [45 67  2  1]]
Compressed array getting the 1st and last rows:  [[45 56]
 [67  5]
 [89  0]
 [45  1]]
Compressed array getting the 1st and 3rd columns:  [[45 23 12 56]
 [89  3  1  0]]


In [35]:
# Copy an ndarray
# using np.copy

np_arr_1 = np.array([[12, 45, 12], 
                     [56, 34, 12], 
                     [8, 12, 23]])

np_arr_2 = np_arr_1
np_arr_3 = np_arr_1.copy()

# Now let's make some changes in np_arr_2 and np_arr_3
np_arr_2[2, 1] = -100
np_arr_3[0, 1] = -500

# Now let's print out
print ('np_arr_1 :', np_arr_1)
print ('np_arr_2 :', np_arr_2)
print ('np_arr_3 :', np_arr_3)

# Notice, np_arr_1 gets changed when we change np_arr_2
# But the same doesn't happen when we change an element using np_arr_3
# In the first case, shallow copy happens
# In the second case, deep copy happens

np_arr_1 : [[  12   45   12]
 [  56   34   12]
 [   8 -100   23]]
np_arr_2 : [[  12   45   12]
 [  56   34   12]
 [   8 -100   23]]
np_arr_3 : [[  12 -500   12]
 [  56   34   12]
 [   8   12   23]]


In [37]:
# Cumulative product along a given axis
# using np.cumprod

arr_1 = np.array([[23, 45, 12], [67, 12, 56]])

# Let's do a cumulative product along the axis
print ('Cumulative product of the entire array             \n: ', arr_1.cumprod())
print ('Cumulative product of the entire array along axis 1\n: ', arr_1.cumprod(axis=1))
print ('Cumulative product of the entire array along axis 0\n: ', arr_1.cumprod(axis=0))

Cumulative product of the entire array             
:  [       23      1035     12420    832140   9985680 559198080]
Cumulative product of the entire array along axis 1
:  [[   23  1035 12420]
 [   67   804 45024]]
Cumulative product of the entire array along axis 0
:  [[  23   45   12]
 [1541  540  672]]


In [38]:
# Cumulative sum along a given axis
# using np.cumsum

arr_1 = np.array([[23, 45, 12], [67, 12, 56]])

# Let's do a cumulative product along the axis
print ('Cumulative sum of the entire array             \n: ', arr_1.cumsum())
print ('Cumulative sum of the entire array along axis 1\n: ', arr_1.cumsum(axis=1))
print ('Cumulative sum of the entire array along axis 0\n: ', arr_1.cumsum(axis=0))

Cumulative sum of the entire array             
:  [ 23  68  80 147 159 215]
Cumulative sum of the entire array along axis 1
:  [[ 23  68  80]
 [ 67  79 135]]
Cumulative sum of the entire array along axis 0
:  [[23 45 12]
 [90 57 68]]


In [41]:
# Return specified diagonals
# using np.diagonal

arr_1 = np.array([[1, 2 ,3], [4, 5, 6], [7, 2, 1]])

# Get the main diagonal
print ('The main diagonal is: ', arr_1.diagonal())
print ('The diagonal 1 offset to the left of the main diagonal: ', arr_1.diagonal(1))
print ('The diagonal 1 offset to the right of the main diagonal: ', arr_1.diagonal(-1))

The main diagonal is:  [1 5 1]
The diagonal 1 offset to the left of the main diagonal:  [2 6]
The diagonal 1 offset to the right of the main diagonal:  [4 2]


In [42]:
# Get the maximum element along the axis
# using np.max

arr_1 = np.array([[1, 2 ,3], [4, 5, 6], [7, 2, 1]])

print ('The max in the entire array is: ', arr_1.max())
print ('The max in the entire array along axis 1 is: ', arr_1.max(axis=1))
print ('The max in the entire array along axis 0 is: ', arr_1.max(axis=0))

The max in the entire array is:  7
The max in the entire array along axis 1 is:  [3 6 7]
The max in the entire array along axis 0 is:  [7 5 6]


In [43]:
# Get the minimum element along the axis
# using np.min

arr_1 = np.array([[1, 2 ,3], [4, 5, 6], [7, 2, 1]])

print ('The min in the entire array is: ', arr_1.min())
print ('The min in the entire array along axis 1 is: ', arr_1.min(axis=1))
print ('The min in the entire array along axis 0 is: ', arr_1.min(axis=0))

The min in the entire array is:  1
The min in the entire array along axis 1 is:  [1 4 1]
The min in the entire array along axis 0 is:  [1 2 1]


In [44]:
# Get the mean of the all the elements along the axis
# using np.mean

arr_1 = np.array([[1, 2 ,3], [4, 5, 6], [7, 2, 1]])

print ('The mean in the entire array is: ', arr_1.mean())
print ('The mean in the entire array along axis 1 is: ', arr_1.mean(axis=1))
print ('The mean in the entire array along axis 0 is: ', arr_1.mean(axis=0))

The mean in the entire array is:  3.4444444444444446
The mean in the entire array along axis 1 is:  [2.         5.         3.33333333]
The mean in the entire array along axis 0 is:  [4.         3.         3.33333333]


In [48]:
# Get the elements of the array that are non-zero
# using np.nonzero

arr_1 = np.array([[1, 0 ,3], 
                  [0, 5, 0], 
                  [7, 2, 0]])

print ('The mean in the entire array is: ', arr_1.nonzero())

# How to interpret the result?
# We can do something like this

print ('A better representation: ', np.transpose(arr_1.nonzero()))

# Each row in the above returned axis is the (i, j) value for all the positive indexes

The mean in the entire array is:  (array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 1]))
A better representation:  [[0 0]
 [0 2]
 [1 1]
 [2 0]
 [2 1]]


In [52]:
# Get the product of the elements in a given axis
# using np.prod

arr_1 = np.array([[1, 2 ,3], 
                  [4, 5, 6], 
                  [7, 2, 1]])

print ('The product of all elements along the col: ', arr_1.prod(axis=0))
print ('The product of all elements along the row: ', arr_1.prod(axis=1))

The product of all elements along the col:  [28 20 18]
The product of all elements along the row:  [  6 120  14]
We get a random value when we do arr_1.prod() without mentioning the axis:  10080


In [62]:
# Replace specified elements of an array with given values.
# using np.put

arr_1 = np.arange(10, 40, 3)

# np.put changes the array implicitly and returns None
arr_1.put([3, 4, 5], [56, 23, 12])
print ('Replace the indexes [3, 4, 5] with [56, 23, 12]: ', arr_1)

Replace the indexes [3, 4, 5] with [56, 23, 12]:  [10 13 16 56 23 12 28 31 34 37]


In [66]:
# Flatten a ndarray
# using np.ravel

arr_1 = np.array([[1, 2 ,3], 
                  [4, 5, 6], 
                  [7, 2, 1]])

print ('Flattened arr_1 with row-major read: ', arr_1.ravel(order='C'))
print ('Flattened arr_1 with col-major read: ', arr_1.ravel(order='F'))

Flattened arr_1 with row-major read:  [1 2 3 4 5 6 7 2 1]
Flattened arr_1 with col-major read:  [1 4 7 2 5 2 3 6 1]


In [68]:
# Repeat the elements of an array
# using np.repeat

arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print ('arr_1 repeated 3 times: ', arr_1.repeat(3))
print ('arr_2 repeated 2 times: ', arr_2.repeat(2))
print ('arr_2 repeated 2 times along axis 1: ', arr_2.repeat(2, axis=1))
print ('arr_2 repeated 2 times along axis 0: ', arr_2.repeat(2, axis=0))

arr_1 repeated 3 times:  [1 1 1 2 2 2 3 3 3 4 4 4]
arr_2 repeated 2 times:  [1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8]
arr_2 repeated 2 times along axis 1:  [[1 1 2 2 3 3 4 4]
 [5 5 6 6 7 7 8 8]]
arr_2 repeated 2 times along axis 0:  [[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [70]:
# Give a new shape to the ndarray
# using np.reshape

arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr_1 = arr_1.reshape(2, 2)
arr_2 = arr_2.reshape(4, 2)

print ('The new shape of arr_1 is: ', arr_1.shape)
print ('The arr_1 is now: ', arr_1)
print ('The new shape of arr_2 is: ', arr_2.shape)
print ('The arr_2 is now: ', arr_2)

The new shape of arr_1 is:  (2, 2)
The arr_1 is now:  [[1 2]
 [3 4]]
The new shape of arr_2 is:  (4, 2)
The arr_2 is now:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
# Round the elements in the ndarray
# using np.round

arr_1 = np.array([[1.34, 5.23, 6.23, 8.232], [5.2324, 734.2323, 121.1222, 7.343]])

# Rounding all elements to 2 decimal places
arr_1 = arr_1.round(2)

print ('The new arr_1 is: \n', arr_1)

The new arr_1 is: 
 [[  1.34   5.23   6.23   8.23]
 [  5.23 734.23 121.12   7.34]]


In [76]:
# Get the index of position where inserting a certain element wouldn't disturb
# the array sortedness
# using np.searchsorted

arr_1 = np.arange(10)

print ('The index where inserting 3 wont disturb the ordering from the left i.e. the first index: ', arr_1.searchsorted(3, side='left'))
print ('The index where inserting 3 wont disturb the ordering from the right i.e. the last index: ', arr_1.searchsorted(3, side='right'))

The index where inserting 3 wont disturb the ordering from the left i.e. the first index:  3
The index where inserting 3 wont disturb the ordering from the right i.e. the last index:  4


In [79]:
# Sort an ndarray
# using np.sort

arr_1 = np.array([45, 2, 78, 23])
arr_2 = np.array([[78, 2, 34, 8, 12], [56, 23, 89, 231, 1]])

arr_1.sort()
arr_2.sort() # we can soecify the axis here

print ('The sorted arr_1 is: \n', arr_1)
print ('The sorted arr_2 is: \n', arr_2)

The sorted arr_1 is: 
 [ 2 23 45 78]
The sorted arr_2 is: 
 [[  2   8  12  34  78]
 [  1  23  56  89 231]]


In [88]:
# Remove single-dimensional entries from the shape of an array.
# using np.squeeze

arr_1 = np.array([[[3], [45], [78]]])

print ('Current Shape of the array: ', arr_1.shape)

arr_1 = arr_1.squeeze()

print ('Squeezed Shape of the array: ', arr_1.shape)

Current Shape of the array:  (1, 3, 1)
Squeezed Shape of the array:  (3,)


In [90]:
# Compute the standard deviation along the specified axis.
# using np.std

arr_1 = np.array([45, 2, 78, 23])
arr_2 = np.array([[78, 2, 34, 8, 12], [56, 23, 89, 231, 1]])

print ('The standard deviation for arr_1 is: ', arr_1.std())
print ('The standard deviation for arr_2 along axis 1 is: ', arr_2.std(axis=1))
print ('The standard deviation for arr_2 along axis 0 is: ', arr_2.std(axis=0))

The standard deviation for arr_1 is:  28.1336097932704
The standard deviation for arr_2 along axis 1 is:  [27.78776709 81.17635124]
The standard deviation for arr_1 along axis 0 is:  [ 11.   10.5  27.5 111.5   5.5]


In [92]:
# Sum of array elements over a given axis.
# using np.sum

arr_1 = np.array([45, 2, 78, 23])
arr_2 = np.array([[78, 2, 34, 8, 12], [56, 23, 89, 231, 1]])

print ('The sum for arr_1 is: ', arr_1.sum())
print ('The sum for arr_2 along axis 1 is: ', arr_2.sum(axis=1))
print ('The sum for arr_1 along axis 0 is: ', arr_2.sum(axis=0))

The sum for arr_1 is:  148
The sum for arr_2 along axis 1 is:  [134 400]
The sum for arr_1 along axis 0 is:  [134  25 123 239  13]


In [99]:
# Interchange two axes of an array.
# using np.swapaxes

arr_1 = np.array([[45, 2, 78, 23], 
                  [45, 23, 67, 12]])

arr_2 = np.array([[78, 2, 34, 8, 12], 
                  [56, 23, 89, 231, 1], 
                  [73, 124, 832, 75, 56]])

print ('Original arr_1      : \n', arr_1)
print ('Original arr_1 shape: ', arr_1.shape)
arr_1 = arr_1.swapaxes(1, 0)
print ('Swaped arr_1: \n', arr_1)
print ('Swaped arr_1 shape: ', arr_1.shape)

print ('Original arr_2      : \n', arr_2)
print ('Original arr_2 shape: ', arr_2.shape)
arr_2 = arr_2.swapaxes(1, 0)
print ('Swaped arr_2: \n', arr_2)
print ('Swaped arr_2 shape: ', arr_2.shape)

Original arr_1      : 
 [[45  2 78 23]
 [45 23 67 12]]
Original arr_1 shape:  (2, 4)
Swaped arr_1: 
 [[45 45]
 [ 2 23]
 [78 67]
 [23 12]]
Swaped arr_1 shape:  (4, 2)
Original arr_2      : 
 [[ 78   2  34   8  12]
 [ 56  23  89 231   1]
 [ 73 124 832  75  56]]
Original arr_2 shape:  (3, 5)
Swaped arr_2: 
 [[ 78  56  73]
 [  2  23 124]
 [ 34  89 832]
 [  8 231  75]
 [ 12   1  56]]
Swaped arr_2 shape:  (5, 3)


In [102]:
# Take a random permutation of the array
# using np.random.permutation

arr_1 = np.arange(12, 35, 2)

perm_arr_1 = np.random.permutation(arr_1)

print ('A random permutation of arr_1 is: ', perm_arr_1)

A random permutation of arr_1 is:  [14 24 28 32 26 30 16 34 12 18 20 22]


In [105]:
# Take elements from an array along an axis.
# using np.take

arr_1 = np.random.permutation(np.arange(2, 45, 3))
print ('The arr_1 is: ', arr_1)

arr_take_1 = arr_1.take([2, 3, 4, 5])
arr_take_2 = arr_1.take([[4, 11], [7, 9]])

print ('Taking out 4 indexes from the np.array: ', arr_take_1)
print ('Taking out 4 indexes in the form of 2d array! :\n', arr_take_2)

The arr_1 is:  [17 44 38  8 11  2 41 35 23 20  5 14 32 26 29]
Taking out 4 indexes from the np.array:  [38  8 11  2]
Taking out 4 indexes in the form of 2d array! :
 [[11 14]
 [35 20]]


In [108]:
# Return the sum along diagonals of the array.
# using np.trace

arr_1 = np.array([[45, 2, 78, 23], 
                  [45, 23, 67, 12],
                  [76, 23, 12, 78]])

arr_2 = np.array([[78, 2, 34, 8, 12], 
                  [56, 23, 89, 231, 1], 
                  [73, 124, 832, 75, 56]])

print ('The trace along arr_1:\n', arr_1.trace())
print ('The trace along arr_2:\n', arr_2.trace())
print ('The trace along arr_2 with offset 1 to the right:\n', arr_1.trace(offset=1))
print ('The trace along arr_2 with offset 1 to the left:\n', arr_1.trace(offset=-1))

The trace along arr_1:
 80
The trace along arr_2:
 933
The trace along arr_2 with offset 1 to the right:
 147
The trace along arr_2 with offset 1 to the left:
 68


In [115]:
# Permute the dimensions of an array.
# using np.transpose

arr_1 = np.array([[45, 2, 78, 23], 
                  [45, 23, 67, 12],
                  [76, 23, 12, 78]])

arr_2 = np.zeros((4, 3, 1, 3))

print ('The shape of arr_1 is: ', arr_1.shape)
print ('The shape of arr_2 is: ', arr_2.shape)

print ('The permutation of dims of arr_1:\n', arr_1.transpose(), ' and the shape is: ', arr_1.transpose().shape)
print ('The permutation of dims of arr_2:\n', arr_2.transpose(0, 2, 1, 3), ' and the shape is: ', arr_2.transpose(0, 2, 1, 3).shape)

The shape of arr_1 is:  (3, 4)
The shape of arr_2 is:  (4, 3, 1, 3)
The permutation of dims of arr_1:
 [[45 45 76]
 [ 2 23 23]
 [78 67 12]
 [23 12 78]]  and the shape is:  (4, 3)
The permutation of dims of arr_2:
 [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]  and the shape is:  (4, 1, 3, 3)


In [116]:
# Compute the variance along the specified axis.
# using np.var

arr_1 = np.array([45, 2, 78, 23])
arr_2 = np.array([[78, 2, 34, 8, 12], [56, 23, 89, 231, 1]])

print ('The variance for arr_1 is: ', arr_1.var())
print ('The variance for arr_2 along axis 1 is: ', arr_2.var(axis=1))
print ('The variance for arr_2 along axis 0 is: ', arr_2.var(axis=0))

The variance for arr_1 is:  791.5
The variance for arr_2 along axis 1 is:  [ 772.16 6589.6 ]
The variance for arr_2 along axis 0 is:  [  121.     110.25   756.25 12432.25    30.25]
